[pytest]
; minversion = 7.0
addopts = --html="Test Script Report.html" --self-contained-html
; testpaths =
;     tests
; markers =
;     smoke: Quick sanity check tests
;     slow: Tests that take longer to run